# Copyright 2005 The Android Open Source Project

LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES:= \
	getacd.c

LOCAL_MODULE:= getacd

LOCAL_FORCE_STATIC_EXECUTABLE := true
LOCAL_MODULE_PATH := $(TARGET_ROOT_OUT)
LOCAL_UNSTRIPPED_PATH := $(TARGET_ROOT_OUT_UNSTRIPPED)

LOCAL_STATIC_LIBRARIES := libcutils libc

LOCAL_STATIC_LIBRARIES += CC6_UMIP_ACCESS CC6_ALL_BASIC_LIB libcrypto_static
LOCAL_C_INCLUDES += $(TARGET_OUT_HEADERS)/chaabi

include $(BUILD_EXECUTABLE)
